/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gencturk
 */
public class AddEmployee extends javax.swing.JFrame {

    MainFrame mainFrame;
    /**
     * Creates new form AddEmployee
     */
    public AddEmployee(MainFrame m) {
        initComponents();
        mainFrame = m;
    }
    
    public void initalize()
    {
        ssnTF.setText("");
        nameTF.setText("");
        surnameTF.setText("");
        ageTF.setText("");
        salaryTF.setText("");
        commissionTF.setText("");
        resultLB.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLB = new javax.swing.JLabel();
        ssnLB = new javax.swing.JLabel();
        nameLB = new javax.swing.JLabel();
        surnameLB = new javax.swing.JLabel();
        ageLB = new javax.swing.JLabel();
        salaryLB = new javax.swing.JLabel();
        commissionLB = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        surnameTF = new javax.swing.JTextField();
        ssnTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        salaryTF = new javax.swing.JTextField();
        commissionTF = new javax.swing.JTextField();
        addBT = new javax.swing.JToggleButton();
        resultLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headerLB.setText("NEW SALES REPRESENTATIVE");

        ssnLB.setText("SSN : ");

        nameLB.setText("Name : ");

        surnameLB.setText("Surname : ");

        ageLB.setText("Age : ");

        salaryLB.setText("Base Salary:");

        commissionLB.setText("Commission % :");

        addBT.setText("Add Sales Representative");
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLB)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addBT)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(commissionLB)
                                    .addComponent(salaryLB)
                                    .addComponent(ageLB)
                                    .addComponent(surnameLB)
                                    .addComponent(nameLB)
                                    .addComponent(ssnLB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(surnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ssnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salaryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(commissionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(resultLB, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(headerLB)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnLB)
                    .addComponent(ssnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLB)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLB)
                    .addComponent(surnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLB)
                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryLB)
                    .addComponent(salaryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commissionLB)
                    .addComponent(commissionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultLB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        // TODO add your handling code here:
        try
        {            
            if(SalesRepSys.addSalesRep(new SalesRepresentative(ssnTF.getText(),
                                                nameTF.getText(),
                                                surnameTF.getText(),
                                                Integer.parseInt(ageTF.getText()),
                                                Double.parseDouble(salaryTF.getText()),
                                                Double.parseDouble(commissionTF.getText()))))
            {
                resultLB.setText("SUCCESS");
                mainFrame.addEmpIdToCB(ssnTF.getText());
                ssnTF.setText("");
                nameTF.setText("");
                surnameTF.setText("");
                ageTF.setText("");  
                salaryTF.setText("");
                commissionTF.setText("");              
            }
            else
                resultLB.setText("ID ALREADY EXISTS!");
        }
        catch(NumberFormatException e)
        {
            resultLB.setText("An error occurred in age, salary or commission!");
        }
    }//GEN-LAST:event_addBTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addBT;
    private javax.swing.JLabel ageLB;
    private javax.swing.JTextField ageTF;
    private javax.swing.JLabel commissionLB;
    private javax.swing.JTextField commissionTF;
    private javax.swing.JLabel headerLB;
    private javax.swing.JLabel nameLB;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel resultLB;
    private javax.swing.JLabel salaryLB;
    private javax.swing.JTextField salaryTF;
    private javax.swing.JLabel ssnLB;
    private javax.swing.JTextField ssnTF;
    private javax.swing.JLabel surnameLB;
    private javax.swing.JTextField surnameTF;
    // End of variables declaration//GEN-END:variables
}
