
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gencturk
 */
public class AddRent extends javax.swing.JFrame {

    MainFrame mainFrame;
    
    /**
     * Creates new form AddRent
     */
    
    public void fillComboBoxes()
    {
        plateCB.removeAllItems();
        plateCB.addItem("None");
        ArrayList<Vehicle> vehicles = VehicleSys.getVehicles();
        for(int i = 0; i < vehicles.size(); i++)
            if(!vehicles.get(i).isRented)
                plateCB.addItem(vehicles.get(i).getLicencePlate());
        custSsnCB.removeAllItems();
        custSsnCB.addItem("None");
        ArrayList<Customer> customers = CustomerSys.getCustomers();
        for(int i = 0; i < customers.size(); i++)
            custSsnCB.addItem(customers.get(i).getSsn());
        empSsnCB.removeAllItems();
        empSsnCB.addItem("None");
        ArrayList<SalesRepresentative> salesReps = SalesRepSys.getSalesReps();
        for(int i = 0; i < salesReps.size(); i++)
            empSsnCB.addItem(salesReps.get(i).getSsn());       
    }
    
    public AddRent(MainFrame m) {
        initComponents();
        mainFrame = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLB = new javax.swing.JLabel();
        plateLB = new javax.swing.JLabel();
        plateCB = new javax.swing.JComboBox<>();
        empSsnLB = new javax.swing.JLabel();
        empSsnCB = new javax.swing.JComboBox<>();
        custSsnCB = new javax.swing.JComboBox<>();
        custSsnLB = new javax.swing.JLabel();
        numDaysLB = new javax.swing.JLabel();
        numDaysTF = new javax.swing.JTextField();
        addBT = new javax.swing.JButton();
        informationPanel = new javax.swing.JPanel();
        vehicleLB = new javax.swing.JLabel();
        brandLB = new javax.swing.JLabel();
        brandTF = new javax.swing.JTextField();
        priceLB = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        employeeLB = new javax.swing.JLabel();
        empNameLB = new javax.swing.JLabel();
        empNameTF = new javax.swing.JTextField();
        customerLB = new javax.swing.JLabel();
        custNameLB = new javax.swing.JLabel();
        custNameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        returnDateLB = new javax.swing.JLabel();
        returnDateTF = new javax.swing.JTextField();
        paymentTF = new javax.swing.JTextField();
        paymentLB = new javax.swing.JLabel();
        discountLB = new javax.swing.JTextArea();
        minAgeLB = new javax.swing.JLabel();
        minAgeTF = new javax.swing.JTextField();
        calculateBT = new javax.swing.JButton();
        resultLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headerLB.setText("ADD NEW RENT");

        plateLB.setText("Vehicle Plate : ");

        plateCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateCBActionPerformed(evt);
            }
        });

        empSsnLB.setText("Employee SSN : ");

        empSsnCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSsnCBActionPerformed(evt);
            }
        });

        custSsnCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custSsnCBActionPerformed(evt);
            }
        });

        custSsnLB.setText("Customer SSN : ");

        numDaysLB.setText("# of days : ");

        numDaysTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDaysTFActionPerformed(evt);
            }
        });

        addBT.setText("Add Rent");
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });

        informationPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        informationPanel.setToolTipText("INFORMATION");

        vehicleLB.setText("Vehicle Information : ");

        brandLB.setText("Brand/Model : ");

        brandTF.setEditable(false);

        priceLB.setText("Daily Price : ");

        priceTF.setEditable(false);

        employeeLB.setText("Employee Information : ");

        empNameLB.setText("Name/Surname : ");

        empNameTF.setEditable(false);

        customerLB.setText("Customer Information : ");

        custNameLB.setText("Name/Surname : ");

        custNameTF.setEditable(false);

        jLabel1.setText("Rent Information : ");

        returnDateLB.setText("Return Date : ");

        returnDateTF.setEditable(false);

        paymentTF.setEditable(false);

        paymentLB.setText("Total Payment : ");

        discountLB.setEditable(false);
        discountLB.setColumns(20);
        discountLB.setRows(5);

        minAgeLB.setText("Min Age : ");

        minAgeTF.setEditable(false);

        javax.swing.GroupLayout informationPanelLayout = new javax.swing.GroupLayout(informationPanel);
        informationPanel.setLayout(informationPanelLayout);
        informationPanelLayout.setHorizontalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationPanelLayout.createSequentialGroup()
                        .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(informationPanelLayout.createSequentialGroup()
                                    .addComponent(brandLB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(vehicleLB)
                                .addComponent(employeeLB)
                                .addGroup(informationPanelLayout.createSequentialGroup()
                                    .addComponent(empNameLB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(empNameTF))
                                .addComponent(customerLB)
                                .addGroup(informationPanelLayout.createSequentialGroup()
                                    .addComponent(custNameLB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(custNameTF)))
                            .addComponent(jLabel1)
                            .addGroup(informationPanelLayout.createSequentialGroup()
                                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymentLB)
                                    .addComponent(returnDateLB))
                                .addGap(18, 18, 18)
                                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(returnDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paymentTF, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addComponent(discountLB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(informationPanelLayout.createSequentialGroup()
                        .addComponent(priceLB)
                        .addGap(18, 18, 18)
                        .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minAgeLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minAgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        informationPanelLayout.setVerticalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vehicleLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLB)
                    .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLB)
                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minAgeLB)
                    .addComponent(minAgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discountLB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(employeeLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNameLB)
                    .addComponent(empNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(customerLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custNameLB)
                    .addComponent(custNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnDateLB)
                    .addComponent(returnDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentLB))
                .addGap(20, 20, 20))
        );

        calculateBT.setText("Calculate Total Payment");
        calculateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empSsnLB)
                            .addComponent(custSsnLB)
                            .addComponent(numDaysLB)
                            .addComponent(plateLB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(custSsnCB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(plateCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(empSsnCB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(numDaysTF, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(calculateBT, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(resultLB, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(informationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(headerLB)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headerLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(informationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBT))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plateLB)
                            .addComponent(plateCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(empSsnLB)
                                    .addComponent(empSsnCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(custSsnLB)
                                    .addComponent(custSsnCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(numDaysLB))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(numDaysTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calculateBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultLB, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plateCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateCBActionPerformed
        // TODO add your handling code here:
        if(plateCB.getSelectedItem() != null)
        {
           Vehicle vehicle = VehicleSys.searchVehicle(plateCB.getSelectedItem().toString());
            if(vehicle != null)
            {
                brandTF.setText(vehicle.getBrand() + " " + vehicle.getModel() + " " + vehicle.getYear());
                priceTF.setText(vehicle.getDailyPrice() + "");
                discountLB.setText(vehicle.getDiscountString());
                minAgeTF.setText(vehicle.getMinAgeToRent() + "");
            }
            else
            {
                brandTF.setText("");
                priceTF.setText("");            
            } 
        }
        
    }//GEN-LAST:event_plateCBActionPerformed

    private void empSsnCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSsnCBActionPerformed
        // TODO add your handling code here:
        if(empSsnCB.getSelectedItem() != null)
        {
            SalesRepresentative salesRep = SalesRepSys.searchSalesRep(empSsnCB.getSelectedItem().toString());
            if(salesRep != null)
                empNameTF.setText(salesRep.getName() + " " + salesRep.getSurname());
            else
                empNameTF.setText("");
        }

    }//GEN-LAST:event_empSsnCBActionPerformed

    private void custSsnCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custSsnCBActionPerformed
        // TODO add your handling code here:
        if(custSsnCB.getSelectedItem() != null)
        {
            Customer customer = CustomerSys.searchCustomer(custSsnCB.getSelectedItem().toString());
            if(customer != null)
                custNameTF.setText(customer.getName() + " " + customer.getSurname() + " (" + customer.getAge() + ")");
            else
                custNameTF.setText(""); 
        }

    }//GEN-LAST:event_custSsnCBActionPerformed

    private void numDaysTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDaysTFActionPerformed


    }//GEN-LAST:event_numDaysTFActionPerformed

    private void calculateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBTActionPerformed
        // TODO add your handling code here:        
        calculatePriceAndDate();
    }//GEN-LAST:event_calculateBTActionPerformed

    private boolean calculatePriceAndDate()
    {
        try
        {
            int days = Integer.parseInt(numDaysTF.getText()); 
            if(days < 1)
                resultLB.setText("# of days must be at least 1");
            else
            {
                SDate date = new SDate();
                date.passDays(days);
                returnDateTF.setText(date.toString());
                Vehicle vehicle = VehicleSys.searchVehicle(plateCB.getSelectedItem().toString());
                if(vehicle == null)
                    resultLB.setText("Selec a Vehicle!");
                else
                {
                    paymentTF.setText(vehicle.calculatePrice(days) + ""); 
                    resultLB.setText("");
                    return true;
                }
            }
        }
        catch(NumberFormatException e)
        {
            resultLB.setText("Enter an integer value for # of days!");
        }
        return false;
    }
    
    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        // TODO add your handling code here:
        if(calculatePriceAndDate())
        {
            Vehicle vehicle = VehicleSys.searchVehicle(plateCB.getSelectedItem().toString());
            Customer customer = CustomerSys.searchCustomer(custSsnCB.getSelectedItem().toString());
            SalesRepresentative salesrep = SalesRepSys.searchSalesRep(empSsnCB.getSelectedItem().toString());
            if(vehicle == null)
            {
                resultLB.setText("Select a car!");
                return;
            }
            else if(customer.getAge() < vehicle.getMinAgeToRent())
            {
                resultLB.setText("Minimum age to rent this car is " + vehicle.getMinAgeToRent());
                return;
            }
            if(customer == null)
            {
                resultLB.setText("Select a customer");
                return;
            }
            if(salesrep == null)
            {
                resultLB.setText("Select a employee");
                return;
            }                
            SDate dropOffDate = new SDate();
            dropOffDate.passDays(Integer.parseInt(numDaysTF.getText()));
            Rent rent = new Rent(salesrep, customer, new SDate(), dropOffDate, vehicle);
            RentSys.addRent(rent);
            vehicle.setIsRented(true);
            mainFrame.addRentIdToCB(rent.getId());
            mainFrame.addPlateToRentedVehicles(vehicle.getLicencePlate());
            plateCB.removeItem(plateCB.getSelectedItem());
            resultLB.setText("SUCCESS");
            plateCB.setSelectedIndex(0);
            custSsnCB.setSelectedIndex(0);
            empSsnCB.setSelectedIndex(0);
            numDaysTF.setText("");
            returnDateTF.setText("");
            paymentTF.setText("");
        }
    }//GEN-LAST:event_addBTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBT;
    private javax.swing.JLabel brandLB;
    private javax.swing.JTextField brandTF;
    private javax.swing.JButton calculateBT;
    private javax.swing.JLabel custNameLB;
    private javax.swing.JTextField custNameTF;
    private javax.swing.JComboBox<String> custSsnCB;
    private javax.swing.JLabel custSsnLB;
    private javax.swing.JLabel customerLB;
    private javax.swing.JTextArea discountLB;
    private javax.swing.JLabel empNameLB;
    private javax.swing.JTextField empNameTF;
    private javax.swing.JComboBox<String> empSsnCB;
    private javax.swing.JLabel empSsnLB;
    private javax.swing.JLabel employeeLB;
    private javax.swing.JLabel headerLB;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel minAgeLB;
    private javax.swing.JTextField minAgeTF;
    private javax.swing.JLabel numDaysLB;
    private javax.swing.JTextField numDaysTF;
    private javax.swing.JLabel paymentLB;
    private javax.swing.JTextField paymentTF;
    private javax.swing.JComboBox<String> plateCB;
    private javax.swing.JLabel plateLB;
    private javax.swing.JLabel priceLB;
    private javax.swing.JTextField priceTF;
    private javax.swing.JLabel resultLB;
    private javax.swing.JLabel returnDateLB;
    private javax.swing.JTextField returnDateTF;
    private javax.swing.JLabel vehicleLB;
    // End of variables declaration//GEN-END:variables
}
