/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gencturk
 */
public class AddVehicle extends javax.swing.JFrame {

    /**
     * Creates new form AddVehicle
     */
    public AddVehicle() {
        initComponents();
        motorPanel.setVisible(false);
        minivanPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehicleType = new javax.swing.ButtonGroup();
        headerLB = new javax.swing.JLabel();
        plateLB = new javax.swing.JLabel();
        plateTF = new javax.swing.JTextField();
        brandTF = new javax.swing.JTextField();
        brandLB = new javax.swing.JLabel();
        modelTF = new javax.swing.JTextField();
        modelLB = new javax.swing.JLabel();
        yearTF = new javax.swing.JTextField();
        yearLB = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        priceLB = new javax.swing.JLabel();
        minAgeTF = new javax.swing.JTextField();
        minAgeLB = new javax.swing.JLabel();
        carRB = new javax.swing.JRadioButton();
        motorRB = new javax.swing.JRadioButton();
        minivanRB = new javax.swing.JRadioButton();
        addBT = new javax.swing.JButton();
        resultLB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        carPanel = new javax.swing.JPanel();
        carNumSeatLB = new javax.swing.JLabel();
        carNumSeatTF = new javax.swing.JTextField();
        fuelTypeLB = new javax.swing.JLabel();
        fuelTypeCB = new javax.swing.JComboBox<>();
        motorPanel = new javax.swing.JPanel();
        helmetTypeLB = new javax.swing.JLabel();
        helmetTypeCB = new javax.swing.JComboBox<>();
        motorPowerLB = new javax.swing.JLabel();
        motorPowerTF = new javax.swing.JTextField();
        minivanPanel = new javax.swing.JPanel();
        weightLB = new javax.swing.JLabel();
        weightTF = new javax.swing.JTextField();
        minivanNumSeatLB = new javax.swing.JLabel();
        minivanNumSeatTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(300, 470));

        headerLB.setText("ADD NEW VEHICLE");

        plateLB.setText("Licence Plate : ");

        brandLB.setText("Brand : ");

        modelLB.setText("Model : ");

        yearLB.setText("Year : ");

        priceLB.setText("Daily Price : ");

        minAgeLB.setText("Minimum Age to Rent : ");

        vehicleType.add(carRB);
        carRB.setSelected(true);
        carRB.setText("Car");
        carRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRBActionPerformed(evt);
            }
        });

        vehicleType.add(motorRB);
        motorRB.setText("Motorcycle");
        motorRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorRBActionPerformed(evt);
            }
        });

        vehicleType.add(minivanRB);
        minivanRB.setText("Minivan");
        minivanRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minivanRBActionPerformed(evt);
            }
        });

        addBT.setText("Add Vehicle");
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        carPanel.setEnabled(false);

        carNumSeatLB.setText("# of Seats : ");

        fuelTypeLB.setText("Fuel type : ");

        fuelTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gas", "Diesel", "LPG" }));

        javax.swing.GroupLayout carPanelLayout = new javax.swing.GroupLayout(carPanel);
        carPanel.setLayout(carPanelLayout);
        carPanelLayout.setHorizontalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(carPanelLayout.createSequentialGroup()
                        .addComponent(fuelTypeLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fuelTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(carPanelLayout.createSequentialGroup()
                        .addComponent(carNumSeatLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carNumSeatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        carPanelLayout.setVerticalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carNumSeatLB)
                    .addComponent(carNumSeatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuelTypeLB)
                    .addComponent(fuelTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(carPanel);

        helmetTypeLB.setText("Helmet Type : ");

        helmetTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Face", "Open Face", "Modular", "Half Helmet" }));

        motorPowerLB.setText("Motor Power : ");

        javax.swing.GroupLayout motorPanelLayout = new javax.swing.GroupLayout(motorPanel);
        motorPanel.setLayout(motorPanelLayout);
        motorPanelLayout.setHorizontalGroup(
            motorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motorPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(motorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(motorPowerLB)
                    .addComponent(helmetTypeLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(motorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(helmetTypeCB, 0, 97, Short.MAX_VALUE)
                    .addComponent(motorPowerTF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        motorPanelLayout.setVerticalGroup(
            motorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motorPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(motorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helmetTypeLB)
                    .addComponent(helmetTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(motorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motorPowerLB)
                    .addComponent(motorPowerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(motorPanel);

        weightLB.setText("Weight Capacity : ");

        minivanNumSeatLB.setText("# of Seats : ");

        javax.swing.GroupLayout minivanPanelLayout = new javax.swing.GroupLayout(minivanPanel);
        minivanPanel.setLayout(minivanPanelLayout);
        minivanPanelLayout.setHorizontalGroup(
            minivanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minivanPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(minivanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(minivanPanelLayout.createSequentialGroup()
                        .addComponent(minivanNumSeatLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minivanNumSeatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(minivanPanelLayout.createSequentialGroup()
                        .addComponent(weightLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        minivanPanelLayout.setVerticalGroup(
            minivanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minivanPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(minivanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightLB)
                    .addComponent(weightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(minivanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minivanNumSeatLB)
                    .addComponent(minivanNumSeatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(minivanPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(headerLB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(brandLB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(plateLB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(plateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(modelLB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(yearLB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(priceLB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(minAgeLB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(minAgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(carRB)
                                .addGap(18, 18, 18)
                                .addComponent(motorRB)
                                .addGap(18, 18, 18)
                                .addComponent(minivanRB))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(addBT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(resultLB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(headerLB)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plateLB)
                    .addComponent(plateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLB)
                    .addComponent(brandTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLB)
                    .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLB)
                    .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLB)
                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minAgeLB)
                    .addComponent(minAgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carRB)
                    .addComponent(motorRB)
                    .addComponent(minivanRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultLB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void motorRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorRBActionPerformed
        // TODO add your handling code here:
        carPanel.setVisible(false);
        motorPanel.setVisible(true);
        minivanPanel.setVisible(false);
    }//GEN-LAST:event_motorRBActionPerformed

    private void carRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRBActionPerformed
        // TODO add your handling code here:
        carPanel.setVisible(true);
        motorPanel.setVisible(false);
        minivanPanel.setVisible(false);
    }//GEN-LAST:event_carRBActionPerformed

    private void minivanRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minivanRBActionPerformed
        // TODO add your handling code here:
        carPanel.setVisible(false);
        motorPanel.setVisible(false);
        minivanPanel.setVisible(true);
    }//GEN-LAST:event_minivanRBActionPerformed

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        // TODO add your handling code here:
        try
        {            
            if(carRB.isSelected())
            {
                if(VehicleSys.addVehicle(new Car(plateTF.getText(),
                                                brandTF.getText(),
                                                modelTF.getText(),
                                                Integer.parseInt(yearTF.getText()),
                                                Double.parseDouble(priceTF.getText()),
                                                Integer.parseInt(minAgeTF.getText()),
                                                Integer.parseInt(carNumSeatTF.getText()),
                                                fuelTypeCB.getSelectedItem().toString())))
                {
                    resultLB.setText("SUCCESS");
                    plateTF.setText("");
                    modelTF.setText("");
                    brandTF.setText("");
                    yearTF.setText("");
                    priceTF.setText("");
                    minAgeTF.setText("");
                    carNumSeatTF.setText("");
                }         
                else
                    resultLB.setText("ID ALREADY EXISTS!");   
            }
            else if(motorRB.isSelected())
            {
                if(VehicleSys.addVehicle(new Motorcycle(plateTF.getText(),
                                                brandTF.getText(),
                                                modelTF.getText(),
                                                Integer.parseInt(yearTF.getText()),
                                                Double.parseDouble(priceTF.getText()),
                                                Integer.parseInt(minAgeTF.getText()),
                                                helmetTypeCB.getSelectedItem().toString(),
                                                Integer.parseInt(motorPowerTF.getText()))))
                {
                    resultLB.setText("SUCCESS");
                    plateTF.setText("");
                    modelTF.setText("");
                    brandTF.setText("");
                    yearTF.setText("");
                    priceTF.setText("");
                    minAgeTF.setText("");
                    motorPowerTF.setText("");
                }         
                else
                    resultLB.setText("ID ALREADY EXISTS!");                
            }
            else
            {
                if(VehicleSys.addVehicle(new Minivan(plateTF.getText(),
                                                brandTF.getText(),
                                                modelTF.getText(),
                                                Integer.parseInt(yearTF.getText()),
                                                Double.parseDouble(priceTF.getText()),
                                                Integer.parseInt(minAgeTF.getText()),
                                                Double.parseDouble(weightTF.getText()),
                                                Integer.parseInt(minivanNumSeatTF.getText()))))
                {
                    resultLB.setText("SUCCESS");
                    plateTF.setText("");
                    modelTF.setText("");
                    brandTF.setText("");
                    yearTF.setText("");
                    priceTF.setText("");
                    minAgeTF.setText("");
                    weightTF.setText("");
                    minivanNumSeatTF.setText("");
                }         
                else
                    resultLB.setText("ID ALREADY EXISTS!");  
            }
        }
        catch(NumberFormatException e)
        {
            resultLB.setText("Number format exception! Enter a valid number!");
        }
    }//GEN-LAST:event_addBTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBT;
    private javax.swing.JLabel brandLB;
    private javax.swing.JTextField brandTF;
    private javax.swing.JLabel carNumSeatLB;
    private javax.swing.JTextField carNumSeatTF;
    private javax.swing.JPanel carPanel;
    private javax.swing.JRadioButton carRB;
    private javax.swing.JComboBox<String> fuelTypeCB;
    private javax.swing.JLabel fuelTypeLB;
    private javax.swing.JLabel headerLB;
    private javax.swing.JComboBox<String> helmetTypeCB;
    private javax.swing.JLabel helmetTypeLB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minAgeLB;
    private javax.swing.JTextField minAgeTF;
    private javax.swing.JLabel minivanNumSeatLB;
    private javax.swing.JTextField minivanNumSeatTF;
    private javax.swing.JPanel minivanPanel;
    private javax.swing.JRadioButton minivanRB;
    private javax.swing.JLabel modelLB;
    private javax.swing.JTextField modelTF;
    private javax.swing.JPanel motorPanel;
    private javax.swing.JLabel motorPowerLB;
    private javax.swing.JTextField motorPowerTF;
    private javax.swing.JRadioButton motorRB;
    private javax.swing.JLabel plateLB;
    private javax.swing.JTextField plateTF;
    private javax.swing.JLabel priceLB;
    private javax.swing.JTextField priceTF;
    private javax.swing.JLabel resultLB;
    private javax.swing.ButtonGroup vehicleType;
    private javax.swing.JLabel weightLB;
    private javax.swing.JTextField weightTF;
    private javax.swing.JLabel yearLB;
    private javax.swing.JTextField yearTF;
    // End of variables declaration//GEN-END:variables
}
