
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gencturk
 */
public class MainFrame extends javax.swing.JFrame {

    AddCustomer addCustomer = new AddCustomer(this);
    AddEmployee addEmployee = new AddEmployee(this);
    AddVehicle addVehicle = new AddVehicle();
    AddRent addRent = new AddRent(this);
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        CustomerSys.readTextFile();
        fillCustomerIds();
        
        SalesRepSys.readTextFile();
        fillEmployeeIds();
        
        VehicleSys.readTextFile();
        fillRentedVehiclePlates();
        
        RentSys.readTextFile();
        fillRentIds();
        
    }

    private void fillRentedVehiclePlates()
    {
        ArrayList<Vehicle> vehicles = VehicleSys.getVehicles();
        for(int i = 0; i < vehicles.size(); i++)
            if(vehicles.get(i).isRented())
                vehiclePlateCB.addItem(vehicles.get(i).getLicencePlate());
    }
    
    public void addPlateToRentedVehicles(String plate)
    {
        vehiclePlateCB.addItem(plate);
    }
    
    private void fillCustomerIds()
    {
        ArrayList<Customer> customers = CustomerSys.getCustomers();
        for(int i = 0; i < customers.size(); i++)
            custIdCB.addItem(customers.get(i).getSsn());
    }
    
    public void addCustIdToCB(String ssn)
    {
        custIdCB.addItem( ssn );
    }
    
    private void fillEmployeeIds()
    {
        ArrayList<SalesRepresentative> salesReps = SalesRepSys.getSalesReps();
        for(int i = 0; i < salesReps.size(); i++)
            empIdCB.addItem(salesReps.get(i).getSsn());
    }
    public void addEmpIdToCB(String ssn)
    {
        empIdCB.addItem( ssn );
    }
    
    private void fillRentIds()
    {
        ArrayList<Rent> rents = RentSys.getRents();
        for(int i = 0; i < rents.size(); i++)
            rentIdCB.addItem(rents.get(i).getId() + "");
    }
    public void addRentIdToCB(int id)
    {
        rentIdCB.addItem(id + "");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehicleSituation = new javax.swing.ButtonGroup();
        container = new javax.swing.JTabbedPane();
        customerPanel = new javax.swing.JPanel();
        custIdTF = new javax.swing.JLabel();
        custIdCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        custResultTA = new javax.swing.JTextArea();
        custSearchBT = new javax.swing.JButton();
        custDisplayBT = new javax.swing.JButton();
        custAddNewBT = new javax.swing.JButton();
        employeePanel = new javax.swing.JPanel();
        empIdLB = new javax.swing.JLabel();
        empIdCB = new javax.swing.JComboBox<>();
        empHeaderLB = new javax.swing.JLabel();
        empMonthLB = new javax.swing.JLabel();
        empMonthCB = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        empResultTA = new javax.swing.JTextArea();
        empSearchBT = new javax.swing.JButton();
        empDisplayBT = new javax.swing.JButton();
        empAddNewBT = new javax.swing.JButton();
        vehiclePanel = new javax.swing.JPanel();
        vehicleAllRB = new javax.swing.JRadioButton();
        vehicleAvailableRB = new javax.swing.JRadioButton();
        vehicleCarsCB = new javax.swing.JCheckBox();
        vehicleMotorsCB = new javax.swing.JCheckBox();
        vehicleMinivansCB = new javax.swing.JCheckBox();
        vehicleDisplayBT = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        vehicleDisplayTA = new javax.swing.JTextArea();
        vehicleAddNewBT = new javax.swing.JButton();
        vehicleReturnLB = new javax.swing.JLabel();
        vehiclePlateCB = new javax.swing.JComboBox<>();
        vehicleSubmitBT = new javax.swing.JButton();
        vehicleResultLB = new javax.swing.JLabel();
        rentPanel = new javax.swing.JPanel();
        rentIdLB = new javax.swing.JLabel();
        rentIdCB = new javax.swing.JComboBox<>();
        rentSearchBT = new javax.swing.JButton();
        rentDisplayBT = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        rentDisplayTA = new javax.swing.JTextArea();
        rentAddNewBT = new javax.swing.JButton();
        generalPanel = new javax.swing.JPanel();
        writeFileBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        custIdTF.setText("ID : ");

        custIdCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        custIdCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIdCBActionPerformed(evt);
            }
        });

        custResultTA.setColumns(20);
        custResultTA.setRows(5);
        jScrollPane1.setViewportView(custResultTA);

        custSearchBT.setText("Search");
        custSearchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custSearchBTActionPerformed(evt);
            }
        });

        custDisplayBT.setText("Display All Customers");
        custDisplayBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custDisplayBTActionPerformed(evt);
            }
        });

        custAddNewBT.setText("Add New Customer");
        custAddNewBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custAddNewBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(customerPanelLayout.createSequentialGroup()
                                .addComponent(custIdTF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custIdCB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custSearchBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(custDisplayBT))))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(custAddNewBT)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custIdTF)
                    .addComponent(custIdCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custSearchBT)
                    .addComponent(custDisplayBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(custAddNewBT)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        container.addTab("Customer System", customerPanel);

        empIdLB.setText("ID : ");

        empIdCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        empHeaderLB.setText("Sales Representative Information");

        empMonthLB.setText("Month : ");

        empMonthCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        empResultTA.setColumns(20);
        empResultTA.setRows(5);
        jScrollPane2.setViewportView(empResultTA);

        empSearchBT.setText("Search");
        empSearchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSearchBTActionPerformed(evt);
            }
        });

        empDisplayBT.setText("Display All Employees");
        empDisplayBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empDisplayBTActionPerformed(evt);
            }
        });

        empAddNewBT.setText("Add New Employee");
        empAddNewBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empAddNewBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout employeePanelLayout = new javax.swing.GroupLayout(employeePanel);
        employeePanel.setLayout(employeePanelLayout);
        employeePanelLayout.setHorizontalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empHeaderLB)
                            .addGroup(employeePanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(empIdLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empIdCB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(employeePanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(empSearchBT))
                            .addGroup(employeePanelLayout.createSequentialGroup()
                                .addComponent(empMonthLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empMonthCB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(empAddNewBT)
                                .addComponent(empDisplayBT)))))
                .addGap(9, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );
        employeePanelLayout.setVerticalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addComponent(empHeaderLB)
                        .addGap(18, 18, 18)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empIdLB)
                            .addComponent(empIdCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empMonthCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empMonthLB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empSearchBT)
                        .addGap(56, 56, 56)
                        .addComponent(empDisplayBT)
                        .addGap(40, 40, 40)
                        .addComponent(empAddNewBT)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        container.addTab("Employee System", employeePanel);

        vehicleSituation.add(vehicleAllRB);
        vehicleAllRB.setText("All");
        vehicleAllRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleAllRBActionPerformed(evt);
            }
        });

        vehicleSituation.add(vehicleAvailableRB);
        vehicleAvailableRB.setSelected(true);
        vehicleAvailableRB.setText("Available");

        vehicleCarsCB.setSelected(true);
        vehicleCarsCB.setText("Cars");

        vehicleMotorsCB.setSelected(true);
        vehicleMotorsCB.setText("Motorcycles");

        vehicleMinivansCB.setSelected(true);
        vehicleMinivansCB.setText("Minivans");

        vehicleDisplayBT.setText("Display");
        vehicleDisplayBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleDisplayBTActionPerformed(evt);
            }
        });

        vehicleDisplayTA.setColumns(20);
        vehicleDisplayTA.setRows(5);
        jScrollPane3.setViewportView(vehicleDisplayTA);

        vehicleAddNewBT.setText("Add New Vehicle");
        vehicleAddNewBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleAddNewBTActionPerformed(evt);
            }
        });

        vehicleReturnLB.setText("Rented Vehicles : ");

        vehiclePlateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        vehicleSubmitBT.setText("Has Returned");
        vehicleSubmitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleSubmitBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehiclePanelLayout = new javax.swing.GroupLayout(vehiclePanel);
        vehiclePanel.setLayout(vehiclePanelLayout);
        vehiclePanelLayout.setHorizontalGroup(
            vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiclePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addComponent(vehicleAllRB)
                        .addGap(18, 18, 18)
                        .addComponent(vehicleAvailableRB))
                    .addComponent(vehicleSubmitBT)
                    .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(vehicleReturnLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vehicleDisplayBT)
                        .addComponent(vehiclePlateCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(vehicleCarsCB)
                    .addComponent(vehicleMotorsCB)
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(vehicleAddNewBT))
                    .addComponent(vehicleResultLB, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleMinivansCB))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
        );
        vehiclePanelLayout.setVerticalGroup(
            vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiclePanelLayout.createSequentialGroup()
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleAllRB)
                            .addComponent(vehicleAvailableRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleCarsCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleMotorsCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleMinivansCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleDisplayBT)
                        .addGap(36, 36, 36)
                        .addComponent(vehicleReturnLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehiclePlateCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleSubmitBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleResultLB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vehicleAddNewBT))
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        container.addTab("Vehicle System", vehiclePanel);

        rentIdLB.setText("Rent Id : ");

        rentIdCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        rentSearchBT.setText("Search");
        rentSearchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentSearchBTActionPerformed(evt);
            }
        });

        rentDisplayBT.setText("Display All Rents");
        rentDisplayBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentDisplayBTActionPerformed(evt);
            }
        });

        rentDisplayTA.setColumns(20);
        rentDisplayTA.setRows(5);
        jScrollPane4.setViewportView(rentDisplayTA);

        rentAddNewBT.setText("Add New Rent");
        rentAddNewBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentAddNewBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rentPanelLayout = new javax.swing.GroupLayout(rentPanel);
        rentPanel.setLayout(rentPanelLayout);
        rentPanelLayout.setHorizontalGroup(
            rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rentPanelLayout.createSequentialGroup()
                        .addComponent(rentIdLB)
                        .addGap(18, 18, 18)
                        .addComponent(rentIdCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rentSearchBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rentDisplayBT))
                    .addGroup(rentPanelLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(rentAddNewBT)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        rentPanelLayout.setVerticalGroup(
            rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentIdLB)
                    .addComponent(rentIdCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentSearchBT)
                    .addComponent(rentDisplayBT))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rentAddNewBT)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        container.addTab("Rent System", rentPanel);

        writeFileBT.setText("Save ALL Changes");
        writeFileBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeFileBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(writeFileBT, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(writeFileBT)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        container.addTab("General", generalPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custSearchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custSearchBTActionPerformed
        // TODO add your handling code here:
        Customer customer = CustomerSys.searchCustomer(custIdCB.getSelectedItem().toString());
        if(customer == null)
            custResultTA.setText("Customer NOT FOUND!");
        else
            custResultTA.setText(customer.toString());
    }//GEN-LAST:event_custSearchBTActionPerformed

    private void custDisplayBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custDisplayBTActionPerformed
        // TODO add your handling code here:
        custResultTA.setText(CustomerSys.getCustomersInfo());
    }//GEN-LAST:event_custDisplayBTActionPerformed

    private void custAddNewBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custAddNewBTActionPerformed
        // TODO add your handling code here:
        addCustomer.initialize();
        addCustomer.setVisible(true);
    }//GEN-LAST:event_custAddNewBTActionPerformed

    private void empSearchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSearchBTActionPerformed
        // TODO add your handling code here:
        SalesRepresentative salesRep = SalesRepSys.searchSalesRep(empIdCB.getSelectedItem().toString());
        if(salesRep == null)
            empResultTA.setText("Employee NOT FOUND");
        else
        {
            if(empMonthCB.getSelectedItem().toString().equalsIgnoreCase("none"))
                empResultTA.setText(salesRep.toString());
            else
            {
                int selectedMonth = Integer.parseInt(empMonthCB.getSelectedItem().toString());
                double salary = salesRep.getCommissionOfMonth(selectedMonth);
                empResultTA.setText(salesRep.toString() + "\nCommission in the month " + selectedMonth + " : " + salary);
            }
                
        }
    }//GEN-LAST:event_empSearchBTActionPerformed

    private void empDisplayBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empDisplayBTActionPerformed
        // TODO add your handling code here:
        empResultTA.setText(SalesRepSys.getSalesRepsInfo());
    }//GEN-LAST:event_empDisplayBTActionPerformed

    private void empAddNewBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empAddNewBTActionPerformed
        // TODO add your handling code here:
        addEmployee.initalize();
        addEmployee.setVisible(true);
    }//GEN-LAST:event_empAddNewBTActionPerformed

    private void vehicleAllRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleAllRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleAllRBActionPerformed

    private void vehicleDisplayBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleDisplayBTActionPerformed
        // TODO add your handling code here:
        boolean checkAvailibility = vehicleAvailableRB.isSelected();
        String result = "";
        if(vehicleCarsCB.isSelected())
            result += VehicleSys.getCarsInfo(checkAvailibility);
        if(vehicleMotorsCB.isSelected())
            result += VehicleSys.getMotorsInfo(checkAvailibility);
        if(vehicleMinivansCB.isSelected())
            result += VehicleSys.getMinivansInfo(checkAvailibility);
        if(result.length() != 0)
            vehicleDisplayTA.setText(result);
        else
            vehicleDisplayTA.setText("NO result found!");
    }//GEN-LAST:event_vehicleDisplayBTActionPerformed

    private void vehicleAddNewBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleAddNewBTActionPerformed
        // TODO add your handling code here:
        addVehicle.setVisible(true);
    }//GEN-LAST:event_vehicleAddNewBTActionPerformed

    private void rentAddNewBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentAddNewBTActionPerformed
        // TODO add your handling code here:
        addRent.fillComboBoxes();
        addRent.setVisible(true);
    }//GEN-LAST:event_rentAddNewBTActionPerformed

    private void writeFileBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeFileBTActionPerformed
        // TODO add your handling code here:
        VehicleSys.writeTextFile();
        CustomerSys.writeTextFile();
        SalesRepSys.writeTextFile();
        RentSys.writeTextFile();
    }//GEN-LAST:event_writeFileBTActionPerformed

    private void rentDisplayBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentDisplayBTActionPerformed
        // TODO add your handling code here:
        rentDisplayTA.setText(RentSys.getRentsInfo());
    }//GEN-LAST:event_rentDisplayBTActionPerformed

    private void custIdCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIdCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIdCBActionPerformed

    private void rentSearchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentSearchBTActionPerformed
        // TODO add your handling code here:
        Rent rent = RentSys.searchRent(Integer.parseInt(rentIdCB.getSelectedItem().toString()));
        if(rent == null)         
            rentDisplayTA.setText("No rent found!");
        else
            rentDisplayTA.setText(rent.toString());
            
    }//GEN-LAST:event_rentSearchBTActionPerformed

    private void vehicleSubmitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleSubmitBTActionPerformed
        // TODO add your handling code here:
        if(vehiclePlateCB.getSelectedItem() != null)
        {
            Vehicle vehicle = VehicleSys.searchVehicle(vehiclePlateCB.getSelectedItem().toString());
            vehicle.setIsRented(false);
            vehicleResultLB.setText("Success");
            vehiclePlateCB.removeItem(vehiclePlateCB.getSelectedItem());           
        }
    }//GEN-LAST:event_vehicleSubmitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane container;
    private javax.swing.JButton custAddNewBT;
    private javax.swing.JButton custDisplayBT;
    private javax.swing.JComboBox<String> custIdCB;
    private javax.swing.JLabel custIdTF;
    private javax.swing.JTextArea custResultTA;
    private javax.swing.JButton custSearchBT;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JButton empAddNewBT;
    private javax.swing.JButton empDisplayBT;
    private javax.swing.JLabel empHeaderLB;
    private javax.swing.JComboBox<String> empIdCB;
    private javax.swing.JLabel empIdLB;
    private javax.swing.JComboBox<String> empMonthCB;
    private javax.swing.JLabel empMonthLB;
    private javax.swing.JTextArea empResultTA;
    private javax.swing.JButton empSearchBT;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton rentAddNewBT;
    private javax.swing.JButton rentDisplayBT;
    private javax.swing.JTextArea rentDisplayTA;
    private javax.swing.JComboBox<String> rentIdCB;
    private javax.swing.JLabel rentIdLB;
    private javax.swing.JPanel rentPanel;
    private javax.swing.JButton rentSearchBT;
    private javax.swing.JButton vehicleAddNewBT;
    private javax.swing.JRadioButton vehicleAllRB;
    private javax.swing.JRadioButton vehicleAvailableRB;
    private javax.swing.JCheckBox vehicleCarsCB;
    private javax.swing.JButton vehicleDisplayBT;
    private javax.swing.JTextArea vehicleDisplayTA;
    private javax.swing.JCheckBox vehicleMinivansCB;
    private javax.swing.JCheckBox vehicleMotorsCB;
    private javax.swing.JPanel vehiclePanel;
    private javax.swing.JComboBox<String> vehiclePlateCB;
    private javax.swing.JLabel vehicleResultLB;
    private javax.swing.JLabel vehicleReturnLB;
    private javax.swing.ButtonGroup vehicleSituation;
    private javax.swing.JButton vehicleSubmitBT;
    private javax.swing.JButton writeFileBT;
    // End of variables declaration//GEN-END:variables
}
